export const config = {
  MESSAGE_DELAY_MS: 500,
  INITIAL_WAIT_MS: 30000,
  SCROLL_DELAY_MS: 200,
  BACK_BUTTON_TIMEOUT_MS: 5000,
  ATTACHMENT_TIMEOUT_MS: 10000,
  MESSAGE_BOX_TIMEOUT_MS: 20000,
  WHATSAPP_TIMEOUT_MS: 90000,
  WHATSAPP_READY_TIMEOUT_MS: 60000,
  CHAT_LIST_SETTLE_TIMEOUT_MS: 4000,
  SEND_CONFIRM_TIMEOUT_MS: 15000,
  SEND_RETRY_MAX: 2,
  SEND_RETRY_DELAY_MS: 2000,

  DEFAULT_SEND_LIMIT: 200,
  LOOP_QUANTITY: 10,
  SCROLL_ITERATIONS: 30,
  SCROLL_AFTER_SENDS: 2,
  SCROLL_DISTANCE: 12,

  BROWSER_VIEWPORT: { width: 1280, height: 800 },
  BROWSER_SLOW_MO: 50,

  WHATSAPP_URL: 'https://web.whatsapp.com'
} as const;

export type AutomationConfig = typeof config;
